exam 1
anahittum/java-lvl-1 pull request #10
Opened 2022-01-31 17:50 UTC by anahittum

2022-02-01 16:16 UTC, gevorgyanarman requested changes

2022-02-01 16:16 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/Exam.java
> +    Scanner scanner = new Scanner(System.in);
this can be a private

2022-02-01 16:16 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/Exam.java
> +        int average;
why is this declared here? the variable declaration should be as close to its first usage as possible. you can even not use it

2022-02-01 16:16 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/Exam.java
> +            return 0;
What if array contains 0 value(s)

2022-02-01 16:16 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/Exam.java
> +    public void endGame() {
the existence of this method is not clear to me

2022-02-01 16:16 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/ExamTest.java
> +        System.out.println(exam.max());
where is the function selection method? why you hardcoded the method invocations?

2022-02-03 07:57 UTC, anahittum commented on src/com/aca/exam/exam1/Exam.java
> +    public void endGame() {
The method asks the user to input a value and the program is not terminated until the user input is 8.

2022-02-05 14:57 UTC, gevorgyanarman requested changes

2022-02-05 14:57 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/Exam.java
> +    public int[] getInputArray() {
if the method didn't change the global array variable but instead create a new one, the method return type would be justified. so either make it void or create a new array and return it and assign global array to the one returned by this method

2022-02-05 14:57 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/ExamTest.java
> +        exam.methodSelector();
here you have a single game. please make it repeatable until the user writes 8 number

2022-02-06 07:48 UTC, gevorgyanarman requested changes

2022-02-06 07:48 UTC, gevorgyanarman commented on src/com/aca/exam/exam1/Exam.java
> +                    System.exit(0);
We use System.exit in extreme situations. imagine a case where you should do some other processes when this method relation loop ends. please try to find a better alterative to stop the while loop

2022-02-06 17:25 UTC, anahittum commented on src/com/aca/exam/exam1/Exam.java
> +                    return;
@gevorgyanarman how about this?

2022-02-08 14:26 UTC, merged