The solution of driving license, user and covid test
anahittum/java-lvl-1 pull request #11
Opened 2022-02-03 10:22 UTC by anahittum

The solution of driving license, user and covid test

2022-02-04 13:03 UTC, gevorgyanarman requested changes

2022-02-04 13:03 UTC, gevorgyanarman commented on src/homeworks/week3/license/covid/test/CovidTest.java
> +        setResult();
let's do not use this method in a Constructor. instead, the covid test might have the "undefined" state, and if someone calls the test method it will set either positive or negative result to this class result field

2022-02-04 13:03 UTC, gevorgyanarman commented on src/homeworks/week3/license/covid/test/CovidTest.java
> +            for (int i = 0; i < possibleResults.length; i++)
every time this code block will be executed. please correct it. would be nice if you had wait3Secs method and wrote the result assignment out of that method to not mix the concepts

2022-02-05 14:10 UTC, anahittum commented on src/homeworks/week3/license/covid/test/CovidTest.java
> +            for (int i = 0; i < possibleResults.length; i++)
Separated the wait for 3 secods into a new method. But I think setting the result via for loop will always generate the same result, am I right?

2022-02-05 14:17 UTC, gevorgyanarman requested changes

2022-02-05 14:17 UTC, gevorgyanarman commented on src/homeworks/week3/license/covid/test/CovidTest.java
> +            this.result = possibleResults[i];
the result is always 'positive'. please set a random value

2022-02-05 14:17 UTC, gevorgyanarman commented on src/homeworks/week3/license/covid/test/CovidTest.java
> +        for (int i = 0; i < possibleResults.length; i++)
it is not desirable to not use { } in loop

2022-02-06 07:35 UTC, gevorgyanarman requested changes
please apply the minor change and merge the pull request

2022-02-06 07:35 UTC, gevorgyanarman commented on src/homeworks/week3/license/covid/test/CovidTest.java
> +            Random random = new Random();
please use ctrl+alt+shift+L to format the code

2022-02-06 17:14 UTC, merged