The solution of the polymorphic car problem
anahittum/java-lvl-1 pull request #15
Opened 2022-02-09 15:07 UTC by anahittum

2022-02-09 17:44 UTC, gevorgyanarman requested changes

2022-02-09 17:44 UTC, gevorgyanarman commented on src/homeworks/week5/car/Car.java
> +public class Car {
The Bmw subclass is missing

2022-02-10 11:55 UTC, anahittum commented on src/homeworks/week5/car/MyTest.java
> +            cars[i] = new Car(scanner.next(), scanner.nextLong(), scanner.nextLong(), scanner.next());
Done.

2022-02-10 11:55 UTC, anahittum commented on src/homeworks/week5/car/Car.java
> +public class Car {
Added.

2022-02-11 07:30 UTC, merged