The solution of the polymorphic exam
anahittum/java-lvl-1 pull request #16
Opened 2022-02-09 18:02 UTC by anahittum

2022-02-09 18:26 UTC, gevorgyanarman requested changes

2022-02-09 18:26 UTC, gevorgyanarman commented on src/homeworks/week5/exam/ExamTest.java
> +    String username;
the field should be private

2022-02-09 19:18 UTC, anahittum commented on src/homeworks/week5/exam/ExamTest.java
> +    String username;
Done. I made the boolean field private and final as well. is this correct?

2022-02-10 05:47 UTC, gevorgyanarman commented on src/homeworks/week5/exam/ExamTest.java
> +    String username;
yes much better

2022-02-10 05:47 UTC, merged