created User class
anahittum/java-lvl-1 pull request #2
Opened 2022-01-21 18:18 UTC by anahittum

created User class

2022-01-21 18:30 UTC, gevorgyanarman requested changes

2022-01-21 18:30 UTC, gevorgyanarman commented on src/homeworks/week2/user/creation/User.java
> +        for (int i = 0; i < userList.length; i++) {
this will create 3x3 users

2022-01-21 18:30 UTC, gevorgyanarman commented on src/homeworks/week2/user/creation/User.java
> +        for (int i = 0; i < userList.length; i++) {
there is no need to create loop here

2022-01-21 18:30 UTC, gevorgyanarman commented on src/homeworks/week2/user/creation/User.java
> +    public static void createUsers(User[] userList) {
wouldn't it be better if createUsers took nothing and returned User[]?

2022-01-21 18:30 UTC, gevorgyanarman commented on src/homeworks/week2/user/creation/User.java
> +            wait1Second();
there was no requirement to wait

2022-01-21 18:32 UTC, anahittum commented on src/homeworks/week2/user/creation/User.java
> +            wait1Second();
Seems that "print all users one by one" implies that.

2022-01-21 18:34 UTC, anahittum commented on src/homeworks/week2/user/creation/User.java
> +    public static void createUsers(User[] userList) {
That's how I did it initially but then printing the users was more complicated so I modified it to this.

2022-01-21 18:37 UTC, anahittum commented on src/homeworks/week2/user/creation/User.java
> +        for (int i = 0; i < userList.length; i++) {
Corrected.

2022-01-21 19:03 UTC, gevorgyanarman requested changes

2022-01-21 19:03 UTC, gevorgyanarman commented on src/homeworks/week2/user/creation/User.java
> +    public static void createUsers(User[] userList) {
Although it works it is better to pass nothing but to get an array

2022-01-21 19:03 UTC, gevorgyanarman commented on src/homeworks/week2/user/creation/User.java
> +            createUsers(userList);
please remove the extra spaces

2022-01-21 19:35 UTC, anahittum commented on src/homeworks/week2/user/creation/User.java
> +            createUsers(userList);
Done.

2022-01-25 14:52 UTC, anahittum commented on src/homeworks/week2/user/creation/User.java
> +    public static void createUsers(User[] userList) {
Done.

2022-01-25 16:14 UTC, merged