The solution of the 'credit card' problem
anahittum/java-lvl-1 pull request #35
Opened 2022-03-02 11:02 UTC by anahittum

2022-03-03 12:55 UTC, gevorgyanarman requested changes

2022-03-03 12:55 UTC, gevorgyanarman commented on src/main/com/homeworks/week8/credit/card/CreditCard.java
> +    double balance;
should be private

2022-03-03 12:55 UTC, gevorgyanarman commented on src/main/com/homeworks/week8/credit/card/InsufficientBalanceException.java
> +
the message argument is ignored. please pass it to super class

2022-03-03 12:55 UTC, gevorgyanarman commented on src/test/com/homeworks/week8/credit/card/PaymentServiceTest.java
> +                for (int i = 0; i < 4; i++) {
here you can not be sure that the exception is thrown right after the 4th invocation.

2022-03-04 11:38 UTC, anahittum commented on src/main/com/homeworks/week8/credit/card/CreditCard.java
> +    double balance;
Fixed everything but this. Can you please advice how to handle the corresponding changes in pay() method?

2022-03-04 20:14 UTC, gevorgyanarman requested changes

2022-03-04 20:14 UTC, gevorgyanarman commented on src/main/com/homeworks/week8/credit/card/PaymentService.java
> +            throw new InsufficientBalanceException("Not enough balance on the card");
please pass the amount to be paid and balance to the message

2022-03-04 20:14 UTC, gevorgyanarman commented on src/test/com/homeworks/week8/credit/card/PaymentServiceTest.java
> +        });
please assert the exception message too

2022-03-05 10:43 UTC, gevorgyanarman requested changes

2022-03-05 10:43 UTC, gevorgyanarman commented on src/main/com/homeworks/week8/credit/card/CreditCard.java
> +    public void debit(double amount) {
let's throw an exception if the amount is bigger than the balance

2022-03-05 11:25 UTC, anahittum commented on src/test/com/homeworks/week8/credit/card/PaymentServiceTest.java
> +        });
added a new test for that

2022-03-05 18:34 UTC, merged