The solution of the 'expression calculator' problem
anahittum/java-lvl-1 pull request #38
Opened 2022-03-06 19:20 UTC by anahittum

2022-03-06 19:39 UTC, gevorgyanarman requested changes

2022-03-06 19:39 UTC, gevorgyanarman commented on src/main/com/homeworks/week9/calculator/SimpleCalculator.java
> +        if (expression.contains("*")) {
Let's create an OperationType enum class and move calculation logic there.

2022-03-06 19:39 UTC, gevorgyanarman commented on src/main/com/homeworks/week9/calculator/SimpleCalculator.java
> +        if (!expression.matches("^[0-9]+[-,*,+,/]{1}+\\d+$")) {
well done

2022-03-07 06:49 UTC, anahittum commented on src/main/com/homeworks/week9/calculator/SimpleCalculator.java
> +        if (expression.contains("*")) {
done

2022-03-09 07:41 UTC, gevorgyanarman requested changes

2022-03-09 07:41 UTC, gevorgyanarman commented on src/main/com/homeworks/week9/calculator/OperationType.java
> +    public abstract String calculate(String expression);
let's change the method signature to expect 2 integer numbers

2022-03-09 07:41 UTC, gevorgyanarman commented on src/main/com/homeworks/week9/calculator/OperationType.java
> +    public abstract String calculate(String expression);
the operation enum should not be aware that it is a part of 'expression' application. it should be independent

2022-03-09 07:41 UTC, gevorgyanarman commented on src/main/com/homeworks/week9/calculator/SimpleCalculator.java
> +        if (expression.contains("-")) {
let's move this ifs to Operation enum class. create a method that will take a char and will return an enum value

2022-03-13 12:31 UTC, merged