created Car class
anahittum/java-lvl-1 pull request #4
Opened 2022-01-22 13:23 UTC by anahittum

created Car class

2022-01-22 15:00 UTC, gevorgyanarman requested changes

2022-01-22 15:00 UTC, gevorgyanarman commented on src/homeworks/week2/cars/Car.java
> +public class Car {
Create a method which takes cars and returns list of cars manufactured after 2010.

The requirement is not done

2022-01-22 15:20 UTC, anahittum commented on src/homeworks/week2/cars/Car.java
> +public class Car {
Please take a look at printSelectedCars() method.

2022-01-25 15:09 UTC, anahittum commented on src/homeworks/week2/cars/Car.java
> +public class Car {
Modified.

2022-01-25 16:13 UTC, gevorgyanarman requested changes

2022-01-25 16:13 UTC, gevorgyanarman commented on src/homeworks/week2/cars/Car.java
> +    private static void printSelectedCars(int year, Car[] cars) {
Still, the code does not meet the requirement. You must create a method that takes a Car[] and returns a new Car array.

2022-01-27 09:54 UTC, closed without merging