created CovidTest class
anahittum/java-lvl-1 pull request #7
Opened 2022-01-25 17:02 UTC by anahittum

The COVID test solution

2022-01-25 17:31 UTC, gevorgyanarman requested changes

2022-01-25 17:31 UTC, gevorgyanarman commented on src/homeworks/week3/covidtest/User.java
> +    public static void print(User user) {
please add non static print method too

2022-01-25 17:31 UTC, gevorgyanarman commented on src/homeworks/week3/covidtest/CovidTest.java
> +    public static void printCovidTest(CovidTest covidTest) {
please add non static print method too

2022-01-27 11:38 UTC, anahittum commented on src/homeworks/week3/covidtest/Main.java
> +        covidTest.printCovidTestNonStatic(covidTest);
@gevorgyanarman does this make sense at all?

2022-01-27 13:38 UTC, gevorgyanarman requested changes

2022-01-27 13:38 UTC, gevorgyanarman commented on src/homeworks/week3/covidtest/CovidTest.java
> +    public void printCovidTestNonStatic(CovidTest covidTest) {
you do not need to pass a covidTest as an argument.

2022-01-27 13:38 UTC, gevorgyanarman commented on src/homeworks/week3/covidtest/Main.java
> +        covidTest.printCovidTestNonStatic(covidTest);
yeah, it does. here you shouldn't pass an object as a method argument cuz in class non static method you have it

2022-01-27 13:38 UTC, gevorgyanarman commented on src/homeworks/week3/covidtest/User.java
> +    public void printNonStatic(User user) {
same here

2022-01-30 20:49 UTC, anahittum commented on src/homeworks/week3/covidtest/Main.java
> +        covidTest.printCovidTestNonStatic(covidTest);
I am not sure I understand your comment. Can you clarify, please?

2022-02-03 07:51 UTC, anahittum commented on src/homeworks/week3/covidtest/CovidTest.java
> +    public void printCovidTestNonStatic(CovidTest covidTest) {
Corrected.

2022-02-05 13:26 UTC, anahittum commented
@gevorgyanarman I have corrected everything you had commented on. Can this PR be merged?

2022-02-05 14:14 UTC, merged